services:
  address-validator:
    build: .
    container_name: address-validator
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production

      SMARTY_AUTH_ID: ${SMARTY_AUTH_ID}
      SMARTY_AUTH_TOKEN: ${SMARTY_AUTH_TOKEN}
